### ISSUE TITLE
怎么卡片滑完之后,再刷新数据,View就出不来了?

### ISSUE THREAD

**Issue by vswe2000** [fashare2015/StackLayout#1]
`    public void setData(List<InteractionResp.DataBean.EachStuListBean> data)
    {
        mData = data;
        notifyDataSetChanged();
    }`

Adapter中这么写的,每次拿到数据就setData

**Comment by fashare2015** [comment]
如果是loadmore的话(当前position不变)，请用`mData.addAll(data); mAdapter.notifyDataSetChanged();`
如果是refresh的话(当前position重置为0),请用`mData=data; mStackLayout.setAdapter(mAdapter=new Adapter(mData));`

**Comment by vswe2000** [comment]
嗯,这个mAdapter是不是必须得重新new一个 不然报` java.lang.IllegalStateException: Observer com.fashare.stack_layout.StackLayout$ItemObserver@13f78f2 is already registered.`

**Comment by fashare2015** [comment]
@vswe2000 是的，这个还得优化一下，先将就用一下

**Comment by vswe2000** [comment]
thanks~
