### ISSUE TITLE
請問一下

### ISSUE THREAD

**Issue by tenSunFree** [fashare2015/StackLayout#2]
為什麼要 乘以3?
![01](https://user-images.githubusercontent.com/23090085/28743162-ae64419c-7475-11e7-8df7-58f29696190d.jpg)

**Comment by fashare2015** [comment]
每次加3条数据，只是测试数据，不用在意。

**Comment by tenSunFree** [comment]
再請問一下, 下面紅框內的代碼, 是否有必要寫? 因為有寫跟沒寫 似乎沒有任何差別?
![02](https://user-images.githubusercontent.com/23090085/28759269-cd9389d4-75cd-11e7-9c5e-9b5884cca551.jpg)

**Comment by fashare2015** [comment]
应该可以不用写

**Comment by tenSunFree** [comment]
了解, 謝謝分享
