### ISSUE TITLE
博主很棒，按着您的思路，学会了很多，但是还有一块不太明白，想请教一下。

### ISSUE THREAD

**Issue by WanDa1993** [fashare2015/StackLayout#4]
第一个问题:
在StackPageTransformer中
```
 else if (position <= bottomPos) { //[0,mStackCount-1] 堆栈中
            int index = (int) position; //取整
            float minScale = mMaxScale * (float) Math.pow(mPowBase, index + 1);
            float maxScale = mMaxScale * (float) Math.pow(mPowBase, index);
```
我读了源码之后,我认为maxScale就是当前Position变化的大小.
而minScale是当前的下一层变化的大小.

这块不太确定,请楼主指点一下.

第二个问题:

第二个问题,我感觉楼主的实现方式是参考RecyclerView和ViewPager,跟着楼主把 这个控件实现,真的学到好多,感觉比以前更清晰了.

那么第二个问题是在这个控件中是否实现了RecyclerView的复用机制.

感谢博主~

**Comment by WanDa1993** [comment]
还有个小建议,Demo里面的  下拉刷新和控件有滑动冲突,楼主有时间可以处理下.以防大家下载后,认为是组件的问题.

**Comment by fashare2015** [comment]
问题1: 栈中比如第4个页面随着pos从4->3，其大小也从minScale->maxScale慢慢变大。它们相当于整数位置的scale，作为页面大小的边界值。
问题2: 并没有实现复用。然而加载时适当分页的话，并不会有问题，控件中同时至多一页多一点的子view。
问题3: 滑动冲突需要找时间修复一下。
Ps:你的六边形recyclerview还不错，找时间学习一下。

**Comment by WanDa1993** [comment]
好的差不多明白啦。感谢~

谢谢夸奖~
